/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursescheduleramg7817;

import java.util.ArrayList;

import java.util.Calendar;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aryan
 */
public class CourseSchedulerFrame extends javax.swing.JFrame {

    /**
     * Creates new form CourseSchedulerFrame
     */
    
    private String currentStudID;
    
    private String currentStudentName;
    
    private String currentSemester;
    

    public CourseSchedulerFrame() {
        
        initComponents();
        
        rebuildSemesterComboBoxes();
        
        rebuildStudentComboBoxes();
    }

    public void rebuildSemesterComboBoxes() {
        
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        
        changeSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));
        
        if (semesters.size() > 0) {
            
            currentSemesterLabel.setText(semesters.get(0));
            
            currentSemester = semesters.get(0);
        
        } else {
            
            currentSemesterLabel.setText("None, add a semester.");
            
            currentSemester = "None";
        }
        
        rebuildCourseComboBoxes();
    
    }

    public void rebuildCourseComboBoxes() {
        
        ArrayList<String> courses = CourseQueries.getAllCourseCodes(currentSemester);
        
        
        scheduleCourseCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        
        adminDisplayCourseListComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        
        adminDropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        
        setStudentDropCourseComboBox();
    
    }

    public void rebuildStudentComboBoxes() {
        
        ArrayList<StudentEntry> students = StudentQueries.getStudentList();
        
        ArrayList<String> studentNames = new ArrayList<>();
        
        for (StudentEntry student : students) {
            
            String name = student.getLastName() + "," + student.getFirstName() + " " + student.getStudentID();
            
            studentNames.add(name);
        
        }
        
        changeStudentComboBox2.setModel(new javax.swing.DefaultComboBoxModel(studentNames.toArray()));
        
        changeStudentComboBox3.setModel(new javax.swing.DefaultComboBoxModel(studentNames.toArray()));
        
        adminDropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(studentNames.toArray()));
        
        changeStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(studentNames.toArray()));
        
        changeStudentComboBox1.setModel(new javax.swing.DefaultComboBoxModel(studentNames.toArray()));
        
        if (students.size() > 0) {
            
            studentTabCurrentStudentLabel1.setText(studentNames.get(0));
            
            studentTabCurrentStudentLabel2.setText(studentNames.get(0));
            
            studentTabCurrentStudentLabel3.setText(studentNames.get(0));
            
            studentTabCurrentStudentLabel.setText(studentNames.get(0));
            
            currentStudID = students.get(0).getStudentID();
            
            currentStudentName = studentNames.get(0);
        } else {
            
            currentStudID = "None";
            
            currentSemesterLabel.setText("None, add a student.");
            
        }

        setStudentDropCourseComboBox();
    }

    public void setStudentDropCourseComboBox() {
        
        ArrayList<ScheduleEntry> sch = ScheduleQueries.getScheduleByStudent(currentSemester, currentStudID);
        
        ArrayList<String> courses = new ArrayList<>();
        
        for (ScheduleEntry entry : sch) {
            
            courses.add(entry.getCourseCode());

        }
        
        studentDropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        changeSemesterComboBox = new javax.swing.JComboBox<>();
        changeSemesterButton = new javax.swing.JButton();
        currentSemesterLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        addSemesterTextfield = new javax.swing.JTextField();
        addSemesterStatusLabel = new javax.swing.JLabel();
        addSemesterSubmitButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        addStudentStudentIDTextfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addStudentFirstNameTextField = new javax.swing.JTextField();
        addStudentLastNameTextField = new javax.swing.JTextField();
        addStudentSubmitButton = new javax.swing.JButton();
        addStudentStatusLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addCourseTextField = new javax.swing.JTextField();
        addCourseDescriptionTextField = new javax.swing.JTextField();
        addCourseSeatsSpinner = new javax.swing.JSpinner();
        addCourseButton = new javax.swing.JButton();
        addCourseStatusLabel = new javax.swing.JLabel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        adminDisplayCourseListComboBox = new javax.swing.JComboBox<>();
        displayCourseListAdminButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayScheduledStudentsAdminTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        displayWaitlistedStudentsAdminTable = new javax.swing.JTable();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        adminDropStudentComboBox = new javax.swing.JComboBox<>();
        adminDropStudentDropButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        adminDropStudentTextarea = new javax.swing.JTextArea();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        adminDropCourseComboBox = new javax.swing.JComboBox<>();
        adminDropCourseDropButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        adminsDropCourseStatusTextArea = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayCoursesTable = new javax.swing.JTable();
        displayCoursesDisplayButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        changeStudentComboBox = new javax.swing.JComboBox<>();
        changeStudentButton = new javax.swing.JButton();
        studentTabCurrentStudentLabel = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        scheduleCourseCourseComboBox = new javax.swing.JComboBox<>();
        scheduleCoursesSubmitButton = new javax.swing.JButton();
        scheduleCourseStatusLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        studentTabCurrentStudentLabel1 = new javax.swing.JLabel();
        changeStudentComboBox1 = new javax.swing.JComboBox<>();
        changeStudentButton1 = new javax.swing.JButton();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayScheduleTable = new javax.swing.JTable();
        displayScheduleDisplayButton = new javax.swing.JButton();
        changeStudentButton2 = new javax.swing.JButton();
        changeStudentComboBox2 = new javax.swing.JComboBox<>();
        studentTabCurrentStudentLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        studentDropCourseComboBox = new javax.swing.JComboBox<>();
        studentDropCourseDropButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        studentDropCourseTextArea = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        studentTabCurrentStudentLabel3 = new javax.swing.JLabel();
        changeStudentComboBox3 = new javax.swing.JComboBox<>();
        changeStudentButton3 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("Course Scheduler");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("Current Semester:");

        changeSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        changeSemesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSemesterComboBoxActionPerformed(evt);
            }
        });

        changeSemesterButton.setText("Change Semester");
        changeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSemesterButtonActionPerformed(evt);
            }
        });

        currentSemesterLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        currentSemesterLabel.setText("None");

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setName(""); // NOI18N

        jLabel5.setText("Semester Name:");

        addSemesterTextfield.setColumns(20);
        addSemesterTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterTextfieldActionPerformed(evt);
            }
        });

        addSemesterStatusLabel.setText("                    ");

        addSemesterSubmitButton.setText("Submit");
        addSemesterSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(addSemesterSubmitButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addSemesterStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addSemesterSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(addSemesterStatusLabel)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Add Semester", jPanel2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Student ID:");
        jLabel4.setPreferredSize(new java.awt.Dimension(52, 13));

        addStudentStudentIDTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentStudentIDTextfieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("First Name:");
        jLabel6.setMaximumSize(new java.awt.Dimension(70, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Last Name:");

        addStudentFirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentFirstNameTextFieldActionPerformed(evt);
            }
        });

        addStudentSubmitButton.setText("Submit");
        addStudentSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(addStudentStudentIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addStudentSubmitButton)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addStudentLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addStudentFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStudentStudentIDTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStudentFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStudentLastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(addStudentSubmitButton)
                .addGap(29, 29, 29)
                .addComponent(addStudentStatusLabel)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Add Student", jPanel3);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Course Code:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Course Description:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Seats:");

        addCourseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseTextFieldActionPerformed(evt);
            }
        });

        addCourseDescriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseDescriptionTextFieldActionPerformed(evt);
            }
        });

        addCourseButton.setText("Submit");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCourseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCourseButton)
                            .addComponent(addCourseSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addCourseStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addCourseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addCourseDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addCourseSeatsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(addCourseButton)
                .addGap(18, 18, 18)
                .addComponent(addCourseStatusLabel)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Add Course", jPanel4);

        jPanel9.setPreferredSize(new java.awt.Dimension(731, 435));

        jLabel13.setText("Select Course:");

        adminDisplayCourseListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        displayCourseListAdminButton.setText("Display");
        displayCourseListAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCourseListAdminButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Scheduled Students:");

        displayScheduledStudentsAdminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last Name", "First Name", "StudentID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(displayScheduledStudentsAdminTable);

        jLabel16.setText("Waitlisted Students:");

        displayWaitlistedStudentsAdminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last Name", "First Name", "StudentID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(displayWaitlistedStudentsAdminTable);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(adminDisplayCourseListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(displayCourseListAdminButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(adminDisplayCourseListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayCourseListAdminButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("", jPanel9);

        jTabbedPane3.addTab("Display Course List of Students", jTabbedPane7);

        jLabel17.setText("Select Student:");

        adminDropStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        adminDropStudentDropButton.setText("Drop Student");
        adminDropStudentDropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDropStudentDropButtonActionPerformed(evt);
            }
        });

        adminDropStudentTextarea.setColumns(20);
        adminDropStudentTextarea.setRows(5);
        jScrollPane5.setViewportView(adminDropStudentTextarea);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminDropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adminDropStudentDropButton))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(adminDropStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDropStudentDropButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("", jPanel10);

        jTabbedPane3.addTab("Drop Student", jTabbedPane8);

        jLabel18.setText("Select Course to be Dropped:");

        adminDropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        adminDropCourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDropCourseComboBoxActionPerformed(evt);
            }
        });

        adminDropCourseDropButton.setText("Drop Course");
        adminDropCourseDropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDropCourseDropButtonActionPerformed(evt);
            }
        });

        adminsDropCourseStatusTextArea.setColumns(20);
        adminsDropCourseStatusTextArea.setRows(5);
        jScrollPane6.setViewportView(adminsDropCourseStatusTextArea);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminDropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adminDropCourseDropButton))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(adminDropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDropCourseDropButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane9.addTab("", jPanel8);

        jTabbedPane3.addTab("Drop Course", jTabbedPane9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        jTabbedPane2.setName("Display Courses"); // NOI18N
        jTabbedPane2.setPreferredSize(new java.awt.Dimension(694, 372));

        displayCoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Description", "Seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(displayCoursesTable);
        displayCoursesTable.getAccessibleContext().setAccessibleName("");
        displayCoursesTable.getAccessibleContext().setAccessibleDescription("");

        displayCoursesDisplayButton.setText("Display");
        displayCoursesDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCoursesDisplayButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setText("Current Student:");

        changeStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        changeStudentButton.setText("Change Student");
        changeStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(displayCoursesDisplayButton)
                .addGap(309, 309, 309))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(studentTabCurrentStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeStudentButton)
                        .addGap(51, 51, 51))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(changeStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeStudentButton)
                    .addComponent(studentTabCurrentStudentLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayCoursesDisplayButton)
                .addGap(48, 48, 48))
        );

        jTabbedPane4.addTab("", jPanel5);

        jTabbedPane2.addTab("Display Courses", jTabbedPane4);

        jLabel11.setText("Select Course:");

        scheduleCourseCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        scheduleCourseCourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleCourseCourseComboBoxActionPerformed(evt);
            }
        });

        scheduleCoursesSubmitButton.setText("Submit");
        scheduleCoursesSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleCoursesSubmitButtonActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel14.setText("Current Student:");

        changeStudentComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        changeStudentButton1.setText("Change Student");
        changeStudentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeStudentButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scheduleCourseStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scheduleCoursesSubmitButton)
                                    .addComponent(scheduleCourseCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(studentTabCurrentStudentLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(changeStudentComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeStudentButton1)
                        .addGap(29, 29, 29))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(studentTabCurrentStudentLabel1)
                    .addComponent(changeStudentComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeStudentButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scheduleCourseCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(scheduleCoursesSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scheduleCourseStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("", jPanel6);

        jTabbedPane2.addTab("Schedule Courses", jTabbedPane5);

        displayScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(displayScheduleTable);

        displayScheduleDisplayButton.setText("Display");
        displayScheduleDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayScheduleDisplayButtonActionPerformed(evt);
            }
        });

        changeStudentButton2.setText("Change Student");
        changeStudentButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeStudentButton2ActionPerformed(evt);
            }
        });

        changeStudentComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel20.setText("Current Student:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(displayScheduleDisplayButton)
                .addContainerGap(316, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(studentTabCurrentStudentLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeStudentComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changeStudentButton2)
                        .addGap(19, 19, 19))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeStudentButton2)
                    .addComponent(changeStudentComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentTabCurrentStudentLabel2)
                    .addComponent(jLabel20))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayScheduleDisplayButton)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("", jPanel7);

        jTabbedPane2.addTab("Display Schedule", jTabbedPane6);

        jLabel19.setText("Select Course:");

        studentDropCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        studentDropCourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDropCourseComboBoxActionPerformed(evt);
            }
        });

        studentDropCourseDropButton.setText("Drop Course");
        studentDropCourseDropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDropCourseDropButtonActionPerformed(evt);
            }
        });

        studentDropCourseTextArea.setColumns(20);
        studentDropCourseTextArea.setRows(5);
        jScrollPane7.setViewportView(studentDropCourseTextArea);

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel21.setText("Current Student:");

        changeStudentComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        changeStudentButton3.setText("Change Student");
        changeStudentButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeStudentButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(studentDropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(studentDropCourseDropButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentTabCurrentStudentLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeStudentComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeStudentButton3)
                .addGap(15, 15, 15))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(studentTabCurrentStudentLabel3)
                    .addComponent(changeStudentComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeStudentButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentDropCourseDropButton)
                    .addComponent(studentDropCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jTabbedPane10.addTab("", jPanel11);

        jTabbedPane2.addTab("Drop Course", jTabbedPane10);

        jTabbedPane1.addTab("Student", jTabbedPane2);
        jTabbedPane2.getAccessibleContext().setAccessibleName("Display Schedule"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentSemesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeSemesterButton)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(changeSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSemesterButton)
                    .addComponent(currentSemesterLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSemesterButtonActionPerformed
        // TODO add your handling code here:
        
        String newSemester = (String) changeSemesterComboBox.getSelectedItem();
        
        currentSemesterLabel.setText(newSemester);
        
        currentSemester = newSemester;
        
        rebuildCourseComboBoxes();
        
    }//GEN-LAST:event_changeSemesterButtonActionPerformed

    private void changeSemesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSemesterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeSemesterComboBoxActionPerformed

    private void addSemesterTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSemesterTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addSemesterTextfieldActionPerformed

    private void addSemesterSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSemesterSubmitButtonActionPerformed
        // TODO add your handling code here:
        String semester = addSemesterTextfield.getText();
        
        SemesterQueries.addSemester(semester);
        
        addSemesterStatusLabel.setText("Semester " + semester + " has been added.");
        
        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_addSemesterSubmitButtonActionPerformed

    private void addStudentStudentIDTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentStudentIDTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentStudentIDTextfieldActionPerformed

    private void addStudentFirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentFirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addStudentFirstNameTextFieldActionPerformed

    private void addStudentSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentSubmitButtonActionPerformed
        // TODO add your handling code here:
        String currentstudentID = addStudentStudentIDTextfield.getText();
        
        String name = addStudentFirstNameTextField.getText();
        
        String LastName = addStudentLastNameTextField.getText();
        
        StudentEntry student = new StudentEntry(currentstudentID, name, LastName);
        
        StudentQueries.addStudent(student);
        
        addStudentStatusLabel.setText(LastName + "," + name + " has been added.");
        
        rebuildStudentComboBoxes();     
    }//GEN-LAST:event_addStudentSubmitButtonActionPerformed

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        // TODO add your handling code here:
        String semester = currentSemesterLabel.getText();
       
        String courseCode = addCourseTextField.getText();
        
        String description = addCourseDescriptionTextField.getText();
        
        int numSeats = (int) addCourseSeatsSpinner.getValue();
        
        CourseQueries.addCourse(semester, courseCode, description, numSeats);
        
        CourseEntry course = new CourseEntry(currentSemester, courseCode, description, numSeats);
        
        addCourseStatusLabel.setText(courseCode + " has been added.");
        
        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_addCourseButtonActionPerformed

    private void displayCoursesDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCoursesDisplayButtonActionPerformed
        // Get array list of courses for the current semester.
        ArrayList<CourseEntry> courses = CourseQueries.getAllCourses(currentSemester);
        
        DefaultTableModel displayCoursesTableModel = (DefaultTableModel) displayCoursesTable.getModel();

        // Display the information in the jtable.
        
        displayCoursesTableModel.setNumRows(0);
        
        Object[] rowData = new Object[3];

        for (CourseEntry course : courses) {
            
            rowData[0] = course.getCourseCode();
            
            rowData[1] = course.getCourseDescription();
            
            rowData[2] = course.getSeats();
            
            displayCoursesTableModel.addRow(rowData);
        
        }
    }//GEN-LAST:event_displayCoursesDisplayButtonActionPerformed

    private void scheduleCoursesSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleCoursesSubmitButtonActionPerformed
        String courseCode = scheduleCourseCourseComboBox.getSelectedItem().toString();

        // determine studentID from combobox of name.
        ArrayList<StudentEntry> students = StudentQueries.getStudentList();

        java.sql.Timestamp timestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        // Get number of seats the course will hold.
        int seatsPossible = CourseQueries.getCourseSeats(currentSemester, courseCode);

        // Get number of seats already reserved.
        int reservedSeats = ScheduleQueries.getScheduledStudentCount(currentSemester, courseCode);

        // check to see if student can be scheduled or goes to wait status.
        if (reservedSeats < seatsPossible) {
            // add student as scheduled.
            
            ScheduleEntry student = new ScheduleEntry(currentSemester, courseCode, currentStudID, "s", timestamp);
            
            ScheduleQueries.addScheduleEntry(student);
            
            scheduleCourseStatusLabel.setText(currentStudentName + " has been scheduled for the class");
        } else {
            // add student as waitlisted.
            
            ScheduleEntry student = new ScheduleEntry(currentSemester, courseCode, currentStudID, "w", timestamp);
            
            ScheduleQueries.addScheduleEntry(student);
            
            scheduleCourseStatusLabel.setText(currentStudentName + " has been waitlisted for the class");

        }
        
        setStudentDropCourseComboBox();
    }//GEN-LAST:event_scheduleCoursesSubmitButtonActionPerformed

    private void scheduleCourseCourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleCourseCourseComboBoxActionPerformed
        // TODO add your handling code here:
        
        String newCourse = (String) scheduleCourseCourseComboBox.getSelectedItem();
        
    }//GEN-LAST:event_scheduleCourseCourseComboBoxActionPerformed

    private void addCourseDescriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseDescriptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCourseDescriptionTextFieldActionPerformed

    private void addCourseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCourseTextFieldActionPerformed

    private void adminDropCourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDropCourseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminDropCourseComboBoxActionPerformed

    private void studentDropCourseDropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDropCourseDropButtonActionPerformed
        String courseCode = studentDropCourseComboBox.getSelectedItem().toString();

        // determine if student is scheduled or waitlisted for the course.
        ArrayList<ScheduleEntry> studentSchedule = ScheduleQueries.getScheduleByStudent(currentSemester, currentStudID);
       
        String status = "";
        
        for (ScheduleEntry entry : studentSchedule) {
            
            if (entry.getCourseCode().equals(courseCode)) {
               
                status = entry.getStatus();
                
                break;
            
            }
        
        }
        
        ScheduleQueries.dropStudentScheduleByCourse(currentSemester, currentStudID, courseCode);
        
        if (status.equals("s")) {
            
            studentDropCourseTextArea.setText(studentTabCurrentStudentLabel.getText() + " has been dropped from " + courseCode + "\n");

            // see if a student needs scheduled from the waitlist.
            
            ArrayList<ScheduleEntry> schedule = ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, courseCode);
            
            if (schedule.size() > 0) {
                
                
                ScheduleQueries.updateScheduleEntry(schedule.get(0));
                
                String studentName = StudentQueries.getStudent(schedule.get(0).getStudentID()).toString();
                
                studentDropCourseTextArea.append(studentName + " has been scheduled into " + courseCode + "\n");
            
            }
            
        } else {
            
            studentDropCourseTextArea.setText(studentTabCurrentStudentLabel.getText() + " has been dropped from the waitlist for " + courseCode + "\n");
        
        }
        
        setStudentDropCourseComboBox();
    }//GEN-LAST:event_studentDropCourseDropButtonActionPerformed

    private void studentDropCourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDropCourseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentDropCourseComboBoxActionPerformed

    private void adminDropCourseDropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDropCourseDropButtonActionPerformed
        // TODO add your handling code here:
        // get the course to be dropped for the semester.
        String courseCode = adminDropCourseComboBox.getSelectedItem().toString();

        // retrieve the list of students scheduled or waitlisted for the course.
        ArrayList<ScheduleEntry> scheduledStudents = ScheduleQueries.getScheduledStudentsByCourse(currentSemester, courseCode);
        
        ArrayList<ScheduleEntry> waitlistedStudents = ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, courseCode);

        // drop the students for the class from the schedule.
        ScheduleQueries.dropScheduleByCourse(currentSemester, courseCode);

        // drop the course from the course table.
        CourseQueries.dropCourse(currentSemester, courseCode);

        // display the students that were scheduled and waitlisted who got dropped.
        adminsDropCourseStatusTextArea.setText("Scheduled students dropped from the course: \n");
        
        for (ScheduleEntry studentEntry : scheduledStudents) {
            // get the sts table entry.
            
            StudentEntry sts = StudentQueries.getStudent(studentEntry.getStudentID());
            
            String name = sts.getLastName() + "," + sts.getFirstName() + " " + sts.getStudentID();
            
            adminsDropCourseStatusTextArea.append(name + "\n");
        
        }
        
        adminsDropCourseStatusTextArea.append("\nWaitlisted students dropped from the course: \n");
        
        for (ScheduleEntry studentEntry : waitlistedStudents) {
            
            // get the student table entry.
            
            StudentEntry sts = StudentQueries.getStudent(studentEntry.getStudentID());
            
            String name = sts.getLastName() + "," + sts.getFirstName() + " " + sts.getStudentID();
            
            adminsDropCourseStatusTextArea.append(name + "\n");
        
        }
        
        rebuildCourseComboBoxes();
    }//GEN-LAST:event_adminDropCourseDropButtonActionPerformed

    private void adminDropStudentDropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDropStudentDropButtonActionPerformed
        // TODO add your handling code here:
        // determine studentID from combobox of name.
        
        ArrayList<StudentEntry> students = StudentQueries.getStudentList();
        
        String studentID = students.get(adminDropStudentComboBox.getSelectedIndex()).getStudentID();

        // drop the student from the list of students.
        
        StudentQueries.dropStudent(studentID);
        
        String studentName = adminDropStudentComboBox.getSelectedItem().toString();
        
        adminDropStudentTextarea.setText(studentName + " dropped from the list of students.\n");

        // get arraylist of semesters.
        
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        // loop through and process for each semester.
        
        for (String semester : semesters) {

            adminDropStudentTextarea.append("\nSemester: " + semester + "\n");
            // determine if student is scheduled or waitlisted for the course.
           
            ArrayList<ScheduleEntry> studentSchedule = ScheduleQueries.getScheduleByStudent(semester, studentID);
            
            String status = "";
            
            for (ScheduleEntry entry : studentSchedule) {
               
                String courseCode = entry.getCourseCode();
                
                ScheduleQueries.dropStudentScheduleByCourse(semester, studentID, courseCode);
                
                status = entry.getStatus();
                
                if (status.equals("s")) {
                    
                    adminDropStudentTextarea.append(studentName + " dropped from " + courseCode + "\n");

                    // see if a student needs scheduled from the waitlist.
                   
                    ArrayList<ScheduleEntry> schedule = ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, courseCode);
                    
                    if (schedule.size() > 0) {
                        //Change the new students status from waitlisted to scheduled.
                        
                        ScheduleQueries.updateScheduleEntry(schedule.get(0));
                        
                        StudentEntry waitlistedStudent = StudentQueries.getStudent(schedule.get(0).getStudentID());
                        
                        String waitlistedStudentName = waitlistedStudent.getLastName() + "," + waitlistedStudent.getFirstName() + " " + waitlistedStudent.getStudentID();
                        
                        adminDropStudentTextarea.append(waitlistedStudentName + " scheduled into " + courseCode + "\n");
                    }
                    
                } else {
                    
                    adminDropStudentTextarea.append(studentName + " dropped from the waitlist for " + courseCode + "\n");
                
                }
            }

        }
        
        rebuildStudentComboBoxes();
    }//GEN-LAST:event_adminDropStudentDropButtonActionPerformed

    private void displayCourseListAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCourseListAdminButtonActionPerformed
        // TODO add your handling code here:
        String courseCode = adminDisplayCourseListComboBox.getSelectedItem().toString();

        // get the list of scheduled students for the course.
        ArrayList<ScheduleEntry> schedule = ScheduleQueries.getScheduledStudentsByCourse(currentSemester, courseCode);
        
        DefaultTableModel displayScheduleTableModel = (DefaultTableModel) displayScheduledStudentsAdminTable.getModel();

        // Display the information in the jtable.
        displayScheduleTableModel.setNumRows(0);
        
        Object[] rowData = new Object[3];

        for (ScheduleEntry entry : schedule) {
            // get the student lastname and firstname from student table.
            
            StudentEntry sts = StudentQueries.getStudent(entry.getStudentID());
            
            rowData[0] = sts.getLastName();
            
            rowData[1] = sts.getFirstName();
            
            rowData[2] = entry.getStudentID();
            
            displayScheduleTableModel.addRow(rowData);
        
        }
        

        // display the waitlisted students in the jtable.
        displayScheduleTableModel = (DefaultTableModel) displayWaitlistedStudentsAdminTable.getModel();

        // get the list of scheduled students for the course.
        schedule = ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, courseCode);

        // Display the information in the jtable.
        displayScheduleTableModel.setNumRows(0);

        for (ScheduleEntry entry : schedule) {
            // get the student lastname and firstname from student table.
            
            StudentEntry sts = StudentQueries.getStudent(entry.getStudentID());
            
            rowData[0] = sts.getLastName();
            
            rowData[1] = sts.getFirstName();
            
            rowData[2] = entry.getStudentID();
            
            displayScheduleTableModel.addRow(rowData);
        }
    }//GEN-LAST:event_displayCourseListAdminButtonActionPerformed

    private void changeStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeStudentButtonActionPerformed
        // TODO add your handling code here:
        
        ArrayList<StudentEntry> sts = StudentQueries.getStudentList();
        
        String studentID = sts.get(changeStudentComboBox.getSelectedIndex()).getStudentID();
        
        studentTabCurrentStudentLabel.setText(changeStudentComboBox.getSelectedItem().toString());
        
        currentStudID = studentID;
        
        currentStudentName = changeStudentComboBox.getSelectedItem().toString();
        
        setStudentDropCourseComboBox();

    }//GEN-LAST:event_changeStudentButtonActionPerformed

    private void changeStudentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeStudentButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<StudentEntry> sts = StudentQueries.getStudentList();
        
        String studentID = sts.get(changeStudentComboBox1.getSelectedIndex()).getStudentID();
        
        studentTabCurrentStudentLabel1.setText(changeStudentComboBox1.getSelectedItem().toString());
        
        currentStudID = studentID;
        
        currentStudentName = changeStudentComboBox1.getSelectedItem().toString();
        
        setStudentDropCourseComboBox();
    }//GEN-LAST:event_changeStudentButton1ActionPerformed

    private void changeStudentButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeStudentButton2ActionPerformed
        // TODO add your handling code here:
        ArrayList<StudentEntry> students = StudentQueries.getStudentList();
        
        String studentID = students.get(changeStudentComboBox2.getSelectedIndex()).getStudentID();
        
        studentTabCurrentStudentLabel2.setText(changeStudentComboBox2.getSelectedItem().toString());
        
        currentStudID = studentID;
       
        currentStudentName = changeStudentComboBox2.getSelectedItem().toString();
        
        setStudentDropCourseComboBox();
    }//GEN-LAST:event_changeStudentButton2ActionPerformed

    private void changeStudentButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeStudentButton3ActionPerformed
        // TODO add your handling code here:
        ArrayList<StudentEntry> sts = StudentQueries.getStudentList();
        
        String studentID = sts.get(changeStudentComboBox3.getSelectedIndex()).getStudentID();
        
        studentTabCurrentStudentLabel3.setText(changeStudentComboBox3.getSelectedItem().toString());
        
        currentStudID = studentID;
        
        currentStudentName = changeStudentComboBox3.getSelectedItem().toString();
        
        setStudentDropCourseComboBox();
    }//GEN-LAST:event_changeStudentButton3ActionPerformed

    private void displayScheduleDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayScheduleDisplayButtonActionPerformed
        // Get array list of courses for the current semester.
        ArrayList<StudentEntry> students = StudentQueries.getStudentList();
        
        ArrayList<ScheduleEntry> sch = ScheduleQueries.getScheduleByStudent(currentSemester, currentStudID);
        
        DefaultTableModel displayScheduleTableModel = (DefaultTableModel) displayScheduleTable.getModel();

        // Display the information in the jtable.
        
        displayScheduleTableModel.setNumRows(0);
        
        Object[] rowData = new Object[2];

        for (ScheduleEntry entry : sch) {
            
            rowData[0] = entry.getCourseCode();
            
            String line = "";
            
            switch (entry.getStatus()) {
                
                case "s":
                    
                    line = "Scheduled";
                    
                    break;
                
                case "w":
                    
                    line = "Waitlisted";
                    
                    break;
            }
            
            rowData[1] = line;
            
            displayScheduleTableModel.addRow(rowData);
        }
    }//GEN-LAST:event_displayScheduleDisplayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new CourseSchedulerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseButton;
    private javax.swing.JTextField addCourseDescriptionTextField;
    private javax.swing.JSpinner addCourseSeatsSpinner;
    private javax.swing.JLabel addCourseStatusLabel;
    private javax.swing.JTextField addCourseTextField;
    private javax.swing.JLabel addSemesterStatusLabel;
    private javax.swing.JButton addSemesterSubmitButton;
    private javax.swing.JTextField addSemesterTextfield;
    private javax.swing.JTextField addStudentFirstNameTextField;
    private javax.swing.JTextField addStudentLastNameTextField;
    private javax.swing.JLabel addStudentStatusLabel;
    private javax.swing.JTextField addStudentStudentIDTextfield;
    private javax.swing.JButton addStudentSubmitButton;
    private javax.swing.JComboBox<String> adminDisplayCourseListComboBox;
    private javax.swing.JComboBox<String> adminDropCourseComboBox;
    private javax.swing.JButton adminDropCourseDropButton;
    private javax.swing.JComboBox<String> adminDropStudentComboBox;
    private javax.swing.JButton adminDropStudentDropButton;
    private javax.swing.JTextArea adminDropStudentTextarea;
    private javax.swing.JTextArea adminsDropCourseStatusTextArea;
    private javax.swing.JButton changeSemesterButton;
    private javax.swing.JComboBox<String> changeSemesterComboBox;
    private javax.swing.JButton changeStudentButton;
    private javax.swing.JButton changeStudentButton1;
    private javax.swing.JButton changeStudentButton2;
    private javax.swing.JButton changeStudentButton3;
    private javax.swing.JComboBox<String> changeStudentComboBox;
    private javax.swing.JComboBox<String> changeStudentComboBox1;
    private javax.swing.JComboBox<String> changeStudentComboBox2;
    private javax.swing.JComboBox<String> changeStudentComboBox3;
    private javax.swing.JLabel currentSemesterLabel;
    private javax.swing.JButton displayCourseListAdminButton;
    private javax.swing.JButton displayCoursesDisplayButton;
    private javax.swing.JTable displayCoursesTable;
    private javax.swing.JButton displayScheduleDisplayButton;
    private javax.swing.JTable displayScheduleTable;
    private javax.swing.JTable displayScheduledStudentsAdminTable;
    private javax.swing.JTable displayWaitlistedStudentsAdminTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JComboBox<String> scheduleCourseCourseComboBox;
    private javax.swing.JLabel scheduleCourseStatusLabel;
    private javax.swing.JButton scheduleCoursesSubmitButton;
    private javax.swing.JComboBox<String> studentDropCourseComboBox;
    private javax.swing.JButton studentDropCourseDropButton;
    private javax.swing.JTextArea studentDropCourseTextArea;
    private javax.swing.JLabel studentTabCurrentStudentLabel;
    private javax.swing.JLabel studentTabCurrentStudentLabel1;
    private javax.swing.JLabel studentTabCurrentStudentLabel2;
    private javax.swing.JLabel studentTabCurrentStudentLabel3;
    // End of variables declaration//GEN-END:variables
}
